CREATE TABLE CATEGORIES (
    CATEGORYID      INT              NOT NULL,
    CATEGORYNAME    VARCHAR(15)      NOT NULL,
    DESCRIPTION     VARCHAR(50),
    PRIMARY KEY (CATEGORYID)
);

CREATE TABLE CUSTOMERS (
    CUSTOMERID      VARCHAR(5)       NOT NULL,
    COMPANYNAME     VARCHAR(40)      NOT NULL,
    CONTACTNAME     VARCHAR(30),
    CONTACTTITLE    VARCHAR(30),
    ADDRESS         VARCHAR(60),
    CITY            VARCHAR(15),
    REGION          VARCHAR(15),
    POSTALCODE      VARCHAR(10),
    COUNTRY         VARCHAR(15),
    PHONE           VARCHAR(24),
    FAX             VARCHAR(24),
    PRIMARY KEY (CUSTOMERID)
);

CREATE TABLE EMPLOYEES (
    EMPLOYEEID         INT              NOT NULL,
    LASTNAME           VARCHAR(20)      NOT NULL,
    FIRSTNAME          VARCHAR(10)      NOT NULL,
    TITLE              VARCHAR(30),
    TITLEOFCOURTESY    VARCHAR(25),
    BIRTHDATE          DATE,
    HIREDATE           DATE,
    ADDRESS            VARCHAR(60),
    CITY               VARCHAR(15),
    REGION             VARCHAR(15),
    POSTALCODE         VARCHAR(10),
    COUNTRY            VARCHAR(15),
    HOMEPHONE          VARCHAR(24),
    EXTENSION          VARCHAR(4),
    NOTES              VARCHAR(700),
    REPORTSTO          INT,
    PRIMARY KEY (EMPLOYEEID)
);

CREATE TABLE ORDERDETAILS (
    ORDERID      INT              NOT NULL,
    PRODUCTID    INT              NOT NULL,
    UNITPRICE    DECIMAL(19, 2)   DEFAULT 0 NOT NULL,
    QUANTITY     INT              DEFAULT 1 NOT NULL,
    DISCOUNT     DECIMAL(5, 2)    DEFAULT 0 NOT NULL,
    PRIMARY KEY (ORDERID, PRODUCTID)
);

CREATE TABLE ORDERS (
    ORDERID           INT              NOT NULL,
    CUSTOMERID        VARCHAR(5),
    EMPLOYEEID        INT,
    ORDERDATE         DATE,
    REQUIREDDATE      DATE,
    SHIPPEDDATE       DATE,
    SHIPVIA           INT,
    FREIGHT           DECIMAL(19, 2)   DEFAULT 0,
    SHIPNAME          VARCHAR(40),
    SHIPADDRESS       VARCHAR(60),
    SHIPCITY          VARCHAR(15),
    SHIPREGION        VARCHAR(15),
    SHIPPOSTALCODE    VARCHAR(10),
    SHIPCOUNTRY       VARCHAR(15),
    PRIMARY KEY (ORDERID)
);

-- 
-- TABLE: PRODUCTS 
--
CREATE TABLE PRODUCTS(
    PRODUCTID          INT               NOT NULL AUTO_INCREMENT,
    PRODUCTNAME        VARCHAR(40)       NOT NULL,
    SUPPLIERID         INT,
    CATEGORYID         INT,
    QUANTITYPERUNIT    VARCHAR(20),
    UNITPRICE          DECIMAL(19,2)     DEFAULT 0,
    UNITSINSTOCK       INT               DEFAULT 0,
    UNITSONORDER       INT               DEFAULT 0,
    REORDERLEVEL       INT               DEFAULT 0,
    DISCONTINUED       TINYINT(1),
    PRIMARY KEY (PRODUCTID)
);
-- 
-- TABLE: SHIPPERS 
--
CREATE TABLE SHIPPERS(
    SHIPPERID      INT           NOT NULL AUTO_INCREMENT,
    COMPANYNAME    VARCHAR(40)   NOT NULL,
    PHONE          VARCHAR(24),
    PRIMARY KEY (SHIPPERID)
);
-- 
-- TABLE: SUPPLIERS 
--
CREATE TABLE SUPPLIERS(
    SUPPLIERID      INT           NOT NULL AUTO_INCREMENT,
    COMPANYNAME     VARCHAR(40)   NOT NULL,
    CONTACTNAME     VARCHAR(30),
    CONTACTTITLE    VARCHAR(30),
    ADDRESS         VARCHAR(60),
    CITY            VARCHAR(15),
    REGION          VARCHAR(15),
    POSTALCODE      VARCHAR(10),
    COUNTRY         VARCHAR(15),
    PHONE           VARCHAR(24),
    FAX             VARCHAR(24),
    PRIMARY KEY (SUPPLIERID)
);

-- 
-- TABLE: PRODUCTS 
--
CREATE TABLE PRODUCTS(
    PRODUCTID          INT               NOT NULL AUTO_INCREMENT,
    PRODUCTNAME        VARCHAR(40)       NOT NULL,
    SUPPLIERID         INT,
    CATEGORYID         INT,
    QUANTITYPERUNIT    VARCHAR(20),
    UNITPRICE          DECIMAL(19,2)     DEFAULT 0,
    UNITSINSTOCK       INT               DEFAULT 0,
    UNITSONORDER       INT               DEFAULT 0,
    REORDERLEVEL       INT               DEFAULT 0,
    DISCONTINUED       TINYINT(1),
    PRIMARY KEY (PRODUCTID)
);
-- 
-- TABLE: SHIPPERS 
--
CREATE TABLE SHIPPERS(
    SHIPPERID      INT           NOT NULL AUTO_INCREMENT,
    COMPANYNAME    VARCHAR(40)   NOT NULL,
    PHONE          VARCHAR(24),
    PRIMARY KEY (SHIPPERID)
);
-- 
-- TABLE: SUPPLIERS 
--
CREATE TABLE SUPPLIERS(
    SUPPLIERID      INT           NOT NULL AUTO_INCREMENT,
    COMPANYNAME     VARCHAR(40)   NOT NULL,
    CONTACTNAME     VARCHAR(30),
    CONTACTTITLE    VARCHAR(30),
    ADDRESS         VARCHAR(60),
    CITY            VARCHAR(15),
    REGION          VARCHAR(15),
    POSTALCODE      VARCHAR(10),
    COUNTRY         VARCHAR(15),
    PHONE           VARCHAR(24),
    FAX             VARCHAR(24),
    PRIMARY KEY (SUPPLIERID)
);



