SELECT COALESCE(
    (SELECT IDW_CUSTOMERS FROM STAR_O.DIM_CUSTOMERS A
     WHERE ID_CUSTOMER = V.CUSTOMERID), -1) AS IDW_CUSTOMERS,
  COALESCE(
    (SELECT IDW_EMPLOYEES FROM STAR_O.DIM_EMPLOYEES A
     WHERE ID_EMPLOYEE = V.EMPLOYEEID), -1) AS IDW_EMPLOYEES,
  COALESCE(
    (SELECT IDW_PRODUCTS FROM STAR_O.DIM_PRODUCTS A
     WHERE ID_PRODUCT = PRO.PRODUCTID
     AND CATEGORYID = CAT.CATEGORYID), -1) AS IDW_PRODUCTS,
  COALESCE(
    (SELECT IDW_SHIPPERS FROM STAR_O.DIM_SHIPPERS A
     WHERE ID_SHIPPER = V.SHIPVIA), -1) AS IDW_SHIPPERS,
  COALESCE(
    (SELECT IDW_GEOGRAFIA FROM STAR_O.DIM_GEOGRAFIA A
     WHERE IDW_GEOGRAFIA = V.ORDERID), V.ORDERID) AS IDW_GEOGRAFIA,
  V.CUSTOMERID,
  V.EMPLOYEEID, 
  V.ORDERID,
  V.ORDERDATE,
  V.REQUIREDDATE,
  V.SHIPPEDDATE,
  V.SHIPVIA,
  V.FREIGHT,
  V.SHIPNAME,
  ORD.UNITPRICE,
  ORD.QUANTITY,
  ORD.DISCOUNT,
  SYSDATE() AS FECHA_CARGA
FROM ORDERS.ORDERS V
JOIN ORDERS.ORDERDETAILS ORD ON ORD.ORDERID = V.ORDERID
JOIN ORDERS.PRODUCTS PRO ON PRO.PRODUCTID = ORD.PRODUCTID
JOIN ORDERS.CATEGORIES CAT ON CAT.CATEGORYID = PRO.CATEGORYID
JOIN ORDERS.SUPPLIERS SUP ON SUP.SUPPLIERID = PRO.SUPPLIERID;
