
-- 
-- TABLE: AGG_ORDERS 
--

CREATE TABLE AGG_ORDERS(
    IDW_EMPLOYEES    INT(10) UNSIGNED NOT NULL,
    IDW_PRODUCTS     INT(10) UNSIGNED NOT NULL,
    IDW_SHIPPERS     INT(10) UNSIGNED NOT NULL,
    IDW_GEOGRAFIA    INT(10) UNSIGNED NOT NULL,
    ID_EMPLOYEE      BIGINT(38) UNSIGNED,
    ID_ORDER         BIGINT(38) UNSIGNED NOT NULL,
    ORDERDATE        DATE             NOT NULL,
    REQUIREDDATE     DATE             NOT NULL,
    SHIPPEDDATE      DATE             NOT NULL,
    SHIPVIA          BIGINT(38) UNSIGNED,
    FREIGHT          DECIMAL(19, 2)    DEFAULT 0,
    SHIPNAME         VARCHAR(40),
    UNITPRICE        INT(10) UNSIGNED,
    QUANTITY         CHAR(10),
    DISCOUNT         INT(10) UNSIGNED,
    FECHA_CARGA      DATE
);

-- 
-- TABLE: DIM_CUSTOMERS 
--

CREATE TABLE DIM_CUSTOMERS(
    IDW_CUSTOMERS       INT(10) UNSIGNED NOT NULL,
    ID_CUSTOMER         VARCHAR(5)      NOT NULL,
    CUSTOMER            VARCHAR(40)     NOT NULL,
    CUSTOMER_CONTACT    VARCHAR(30),
    CONTACTTITLE        VARCHAR(30),
    ADDRESS             VARCHAR(60),
    CITY                VARCHAR(15),
    REGION              VARCHAR(15),
    POSTALCODE          VARCHAR(10),
    COUNTRY             VARCHAR(15),
    PHONE               VARCHAR(24),
    FAX                 VARCHAR(24),
    PK_SYSTEM_SOURCE    INT(10) UNSIGNED,
    SYSTEM_SOURCE       VARCHAR(100),
    START_DATE          DATE,
    END_DATE            DATE,
    CURRENT_FLAG        CHAR(1),
    LOGIN_USER_DW       CHAR(30),
    PRIMARY KEY (IDW_CUSTOMERS)
);




-- 
-- TABLE: DIM_EMPLOYEES 
--

CREATE TABLE DIM_EMPLOYEES(
    IDW_EMPLOYEES      INT(10) UNSIGNED NOT NULL,
    ID_EMPLOYEE        INT(38) UNSIGNED NOT NULL,
    LASTNAME           VARCHAR(20)     NOT NULL,
    FIRSTNAME          VARCHAR(10)     NOT NULL,
    TITLE              VARCHAR(30),
    TITLEOFCOURTESY    VARCHAR(25),
    BIRTHDATE          DATE,
    HIREDATE           DATE,
    ADDRESS            VARCHAR(60),
    CITY               VARCHAR(15),
    REGION             VARCHAR(15),
    POSTALCODE         VARCHAR(10),
    COUNTRY            VARCHAR(15),
    HOMEPHONE          VARCHAR(24),
    EXTENSION          VARCHAR(4),
    NOTES              VARCHAR(700),
    REPORTSTO          INT(38) UNSIGNED,
    STAR_DATE          DATE,
    END_DATE           DATE,
    CURRENT_FLAG       CHAR(1),
    LOGIN_USER_DW      VARCHAR(1),
    PRIMARY KEY (IDW_EMPLOYEES)
);




-- 
-- TABLE: DIM_GEOGRAFIA 
--

CREATE TABLE DIM_GEOGRAFIA(
    IDW_GEOGRAFIA    INT(10) UNSIGNED NOT NULL,
    ADRESS           VARCHAR(200),
    CITY             VARCHAR(200),
    REGION           VARCHAR(200),
    POSTALCODE       VARCHAR(100),
    COUNTRY          VARCHAR(10),
    STAR_DATE        DATE,
    END_DATE         DATE,
    CURRENT_FLAG     CHAR(1),
    LOGIN_USER_DW    VARCHAR(30),
    PRIMARY KEY (IDW_GEOGRAFIA)
);




-- 
-- TABLE: DIM_PRODUCTS 
--

CREATE TABLE DIM_PRODUCTS(
    IDW_PRODUCTS            INT(10) UNSIGNED NOT NULL,
    ID_PRODUCT              INT(38) UNSIGNED NOT NULL,
    PRODUCTNAME             VARCHAR(40)     NOT NULL,
    QUANTITYPERUNIT         VARCHAR(20),
    UNITPRICE               DECIMAL(19, 2)    DEFAULT 0,
    UNITSINSTOCK            SMALLINT(5) UNSIGNED    DEFAULT 0,
    UNITSONORDER            SMALLINT(5) UNSIGNED    DEFAULT 0,
    REORDERLEVEL            SMALLINT(5) UNSIGNED    DEFAULT 0,
    DISCONTINUED            TINYINT(1) UNSIGNED,
    CATEGORYID              INT(38) UNSIGNED,
    CATEGORYNAME            VARCHAR(100),
    DESCRIPTION_CATEGORY    VARCHAR(200),
    SUPPLIERID              INT(38) UNSIGNED,
    SUPPLIER                VARCHAR(100),
    SUPPLIERCONTACT         VARCHAR(100),
    SUPPLIERTITLE           VARCHAR(100),
    ADDRES                  VARCHAR(100),
    CITY                    VARCHAR(100),
    REGION                  VARCHAR(100),
    POSTALCODE              VARCHAR(100),
    COUNTRY                 VARCHAR(100),
    PHONE                   VARCHAR(100),
    FAX                     VARCHAR(100),
    STAR_DATE               DATE,
    END_DATE                DATE,
    CURRENT_FLAG            CHAR(1),
    LOGIN_USER_DW           VARCHAR(30),
    PRIMARY KEY (IDW_PRODUCTS)
);



-- 
-- TABLE: DIM_SHIPPERS 
--

CREATE TABLE DIM_SHIPPERS(
    IDW_SHIPPERS     INT(10)    NOT NULL,
    ID_SHIPPER       INT(38)    NOT NULL,
    SHIPPERS         VARCHAR(40)     NOT NULL,
    PHONE            VARCHAR(24),
    STAR_DATE        DATE,
    END_DATE         DATE,
    CURRENT_FLAG     VARCHAR(1),
    LOGIN_USER_DW    VARCHAR(30),
    CONSTRAINT PK_DIM_SHIPPERS PRIMARY KEY (IDW_SHIPPERS)
);




-- 
-- TABLE: DIM_TIEMPO 
--

CREATE TABLE DIM_TIEMPO(
    FECHA          DATE             NOT NULL,
    DIARIO         NUMBER(19, 2),
    DIASEMANA      VARCHAR2(50),
    DIALABORAL     VARCHAR2(10),
    FERIADO        VARCHAR2(10),
    FINDESEMANA    VARCHAR2(10),
    MESNRO         NUMBER(10, 0),
    MES            VARCHAR2(10),
    PERIODO        VARCHAR2(10),
    TRIMESTRE      VARCHAR2(10),
    SEMESTRE       VARCHAR2(10),
    ANHO           NUMBER(10, 0),
    CONSTRAINT PK_DIM_TIEMPO PRIMARY KEY (FECHA)
)
;



-- 
-- TABLE: FACT_ORDERS 
--

CREATE TABLE FACT_ORDERS (
    IDW_CUSTOMERS   INT(10) UNSIGNED NOT NULL,
    IDW_EMPLOYEES   INT(10) UNSIGNED NOT NULL,
    IDW_PRODUCTS    INT(10) UNSIGNED NOT NULL,
    IDW_SHIPPERS    INT(10) UNSIGNED NOT NULL,
    IDW_GEOGRAFIA   INT(10) UNSIGNED NOT NULL,
    ID_CUSTOMER     VARCHAR(5),
    ID_EMPLOYEE     INT(10) UNSIGNED,
    ID_ORDER        INT(10) UNSIGNED NOT NULL,
    ORDERDATE       DATE NOT NULL,
    REQUIREDDATE    DATE NOT NULL,
    SHIPPEDDATE     DATE NOT NULL,
    SHIPVIA         INT(10) UNSIGNED,
    FREIGHT         DECIMAL(19,2) DEFAULT 0,
    SHIPNAME        VARCHAR(40),
    UNITPRICE       INT(10) UNSIGNED,
    QUANTITY        CHAR(10),
    DISCOUNT        INT(10) UNSIGNED,
    FECHA_CARGA     DATE,
    PRIMARY KEY (ID_ORDER)
);



-- 
-- TABLE: AGG_ORDERS 
--

ALTER TABLE AGG_ORDERS ADD CONSTRAINT FK_EMPLOYEES_AGG_ORDERS
    FOREIGN KEY (IDW_EMPLOYEES)
    REFERENCES DIM_EMPLOYEES(IDW_EMPLOYEES)
;

ALTER TABLE AGG_ORDERS ADD CONSTRAINT FK_GEOGRAFIA_AGG_ORDERS
    FOREIGN KEY (IDW_GEOGRAFIA)
    REFERENCES DIM_GEOGRAFIA(IDW_GEOGRAFIA)
;

ALTER TABLE AGG_ORDERS ADD CONSTRAINT FK_PRODUCTS_AGG_ORDERS
    FOREIGN KEY (IDW_PRODUCTS)
    REFERENCES DIM_PRODUCTS(IDW_PRODUCTS)
;

ALTER TABLE AGG_ORDERS ADD CONSTRAINT FK_SHIPPERS_AGG_ORDERS
    FOREIGN KEY (IDW_SHIPPERS)
    REFERENCES DIM_SHIPPERS(IDW_SHIPPERS)
;

ALTER TABLE AGG_ORDERS ADD CONSTRAINT FK_TIEMPO_ORDERDDATE_AORDERS
    FOREIGN KEY (ORDERDATE)
    REFERENCES DIM_TIEMPO(FECHA)
;

ALTER TABLE AGG_ORDERS ADD CONSTRAINT FK_TIEMPO_REQUIREDDATE_AORDERS
    FOREIGN KEY (REQUIREDDATE)
    REFERENCES DIM_TIEMPO(FECHA)
;

ALTER TABLE AGG_ORDERS ADD CONSTRAINT FK_TIEMPO_SHIPPEDDATE_AORDERS
    FOREIGN KEY (SHIPPEDDATE)
    REFERENCES DIM_TIEMPO(FECHA)
;

-- 
-- TABLE: FACT_ORDERS 
--

ALTER TABLE FACT_ORDERS ADD CONSTRAINT FK_CUSTOMERS_ORDERS 
    FOREIGN KEY (IDW_CUSTOMERS)
    REFERENCES DIM_CUSTOMERS(IDW_CUSTOMERS)
;

ALTER TABLE FACT_ORDERS ADD CONSTRAINT FK_EMPLOYEES_ORDERS 
    FOREIGN KEY (IDW_EMPLOYEES)
    REFERENCES DIM_EMPLOYEES(IDW_EMPLOYEES)
;

ALTER TABLE FACT_ORDERS ADD CONSTRAINT FK_GEOGRAFIA_ORDERS 
    FOREIGN KEY (IDW_GEOGRAFIA)
    REFERENCES DIM_GEOGRAFIA(IDW_GEOGRAFIA)
;

ALTER TABLE FACT_ORDERS ADD CONSTRAINT FK_PRODUCTS_ORDERS 
    FOREIGN KEY (IDW_PRODUCTS)
    REFERENCES DIM_PRODUCTS(IDW_PRODUCTS)
;

ALTER TABLE FACT_ORDERS ADD CONSTRAINT FK_SHIPPERS_ORDERS 
    FOREIGN KEY (IDW_SHIPPERS)
    REFERENCES DIM_SHIPPERS(IDW_SHIPPERS)
;

ALTER TABLE FACT_ORDERS ADD CONSTRAINT FK_TIEMPO_ORDERDATE 
    FOREIGN KEY (ORDERDATE)
    REFERENCES DIM_TIEMPO(FECHA)
;

ALTER TABLE FACT_ORDERS ADD CONSTRAINT FK_TIEMPO_REQUIREDDATE 
    FOREIGN KEY (REQUIREDDATE)
    REFERENCES DIM_TIEMPO(FECHA)
;

ALTER TABLE FACT_ORDERS ADD CONSTRAINT FK_TIEMPO_SHIPPEDDATE 
    FOREIGN KEY (SHIPPEDDATE)
    REFERENCES DIM_TIEMPO(FECHA)
;

