DELIMITER //
CREATE PROCEDURE ETL_DIM_TIEMPO()
BEGIN
  -- VARIABLES GENERALES
  DECLARE V_NOMBRE_PROCESO VARCHAR(30) DEFAULT 'ETL_DIM_TIEMPO';
  DECLARE V_FEC_INICIO DATETIME;
  DECLARE V_FEC_FIN DATETIME;
  DECLARE V_COMENTARIO VARCHAR(255);
  DECLARE V_CANT_REG INT DEFAULT 0;
  DECLARE V_CORRECTO CHAR(1) DEFAULT 'N'; -- INDICADOR DE QUE SI EL PROCESO ESTA CORRECTO O NO
  -- VARIABLES DEL PROCESO
  DECLARE V_TOTAL_DIFERENCIAS INT DEFAULT 0;
  
  SET V_FEC_INICIO = NOW();

  -- CODIGO DEL PROCESO
  -- TRUNCATE TABLE ETL_DIM_TIEMPO;
  INSERT INTO STAR_O.DIM_TIEMPO (FECHA, DIARIO, DIASEMANA, DIALABORAL, FERIADO, FINDESEMANA, MESNRO, MES, PERIODO, TRIMESTRE, SEMESTRE, ANHO)
  SELECT FECHA, DIARIO, DIASEMANA, DIALABORAL, FERIADO, FINDESEMANA, MESNRO, MES, PERIODO, TRIMESTRE, SEMESTRE, ANHO
  FROM STG_DIM_TIEMPO;

  SET V_CANT_REG = ROW_COUNT();
  COMMIT;
  -- FIN CODIGO DEL PROCESO

  SET V_FEC_FIN = NOW();
  SET V_COMENTARIO = CONCAT('EL PROCESO ', V_NOMBRE_PROCESO, ' CULMINO SATISFACTORIAMENTE');
  SET V_CORRECTO = 'S';

  CALL P_Insertar_Info_Proc(V_NOMBRE_PROCESO, V_FEC_INICIO, V_FEC_FIN, V_COMENTARIO, V_CANT_REG, V_CORRECTO);
  COMMIT;

  -- Handle errors
  BEGIN
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    SET V_FEC_FIN = NOW();
    SET V_COMENTARIO = CONCAT('ERROR AL ACTUALIZAR ', V_NOMBRE_PROCESO, ' ', SQLCODE, ' ', SQLERRM);
    CALL P_Insertar_Info_Proc(V_NOMBRE_PROCESO, V_FEC_INICIO, V_FEC_FIN, V_COMENTARIO, V_CANT_REG, V_CORRECTO);
    COMMIT;
  END;
END;
END;

