DELIMITER //

CREATE PROCEDURE ETL_FACT_ORDERS (IN PI_FECHA_INICIAL VARCHAR(10), IN PI_FECHA_FINAL VARCHAR(10))
BEGIN
-- VARIABLES GENERALES
DECLARE V_NOMBRE_PROCESO VARCHAR(30) DEFAULT 'ETL_FACT_ORDERS';
DECLARE V_FEC_INICIO DATE;
DECLARE V_FEC_FIN DATE;
DECLARE V_COMENTARIO VARCHAR(255);
DECLARE V_CANT_REG INT DEFAULT 0;
DECLARE V_CORRECTO CHAR(1) DEFAULT 'N'; -- INDICADOR DE QUE SI EL PROCESO ESTA CORRECTO O NO

-- VARIABLES DEL PROCESO
DECLARE V_FECHA_INICIO DATE;
DECLARE V_FECHA_FIN DATE;
DECLARE v_total_diferencias INT DEFAULT 0;

SET V_FEC_INICIO := NOW();

SET V_FECHA_INICIO := STR_TO_DATE(PI_FECHA_INICIAL, '%Y%m%d');
SET V_FECHA_FIN := STR_TO_DATE(PI_FECHA_FINAL, '%Y%m%d');

-- CODIGO DEL PROCESO
DELETE FROM STAR_O.FACT_ORDERS
WHERE ORDERDATE BETWEEN V_FECHA_INICIO AND V_FECHA_FIN;

INSERT INTO STAR_O.FACT_ORDERS (IDW_CUSTOMERS, IDW_EMPLOYEES, IDW_PRODUCTS, IDW_SHIPPERS, IDW_GEOGRAFIA, ID_CUSTOMER, ID_EMPLOYEE, ID_ORDER, ORDERDATE, REQUIREDDATE, SHIPPEDDATE, SHIPVIA, FREIGHT, SHIPNAME, UNITPRICE, QUANTITY, DISCOUNT, FECHA_CARGA)
SELECT IDW_CUSTOMERS, IDW_EMPLOYEES, IDW_PRODUCTS, IDW_SHIPPERS, IDW_GEOGRAFIA, ID_CUSTOMER, ID_EMPLOYEE, ID_ORDER, ORDERDATE, REQUIREDDATE, SHIPPEDDATE, SHIPVIA, FREIGHT, SHIPNAME, UNITPRICE, QUANTITY, DISCOUNT, FECHA_CARGA
FROM STAGE_O.STG_FACT_ORDERS;

SET V_CANT_REG := ROW_COUNT();

SET V_FEC_FIN := NOW();
SET V_COMENTARIO := CONCAT('EL PROCESO ', V_NOMBRE_PROCESO, ' CULMINO SATISFACTORIAMENTE');
SET V_CORRECTO := 'S';

CALL P_Insertar_Info_Proc(V_NOMBRE_PROCESO, V_FEC_INICIO, V_FEC_FIN, V_COMENTARIO, V_CANT_REG, V_CORRECTO);

COMMIT;
END //

DELIMITER ;
