-- CORRER EN EL BDS ESQUEMA STAR_O
GRANT SELECT, INSERT, UPDATE, DELETE  ON AGG_ORDERS TO STAGE_O;
GRANT SELECT, INSERT, UPDATE, DELETE  ON DIM_CUSTOMERS TO STAGE_O;
GRANT SELECT, INSERT, UPDATE, DELETE  ON DIM_EMPLOYEES TO STAGE_O;
GRANT SELECT, INSERT, UPDATE, DELETE  ON DIM_GEOGRAFIA TO STAGE_O;
GRANT SELECT, INSERT, UPDATE, DELETE  ON DIM_PRODUCTS TO STAGE_O;
GRANT SELECT, INSERT, UPDATE, DELETE  ON DIM_SHIPPERS TO STAGE_O;
GRANT SELECT, INSERT, UPDATE, DELETE  ON DIM_TIEMPO TO STAGE_O;
GRANT SELECT, INSERT, UPDATE, DELETE  ON FACT_ORDERS TO STAGE_O;

-- CORRER EN EL BDS ESQUEMA ORDERS

GRANT SELECT ON CATEGORIES TO STAGE_O;
GRANT SELECT ON CUSTOMERS TO STAGE_O;
GRANT SELECT ON EMPLOYEES TO STAGE_O;
GRANT SELECT ON ORDERDETAILS TO STAGE_O;
GRANT SELECT ON ORDERS TO STAGE_O;
GRANT SELECT ON PRODUCTS TO STAGE_O;
GRANT SELECT ON SHIPPERS TO STAGE_O;
GRANT SELECT ON SUPPLIERS TO STAGE_O;
