DELIMITER //
CREATE PROCEDURE ETL_STG_DIM_TIEMPO()
BEGIN
  DECLARE V_NOMBRE_PROCESO VARCHAR(30) DEFAULT 'ETL_STG_DIM_TIEMPO';
  DECLARE V_FEC_INICIO DATE;
  DECLARE V_FEC_FIN DATE;
  DECLARE V_COMENTARIO VARCHAR(255);
  DECLARE V_CANT_REG INT DEFAULT 0;
  DECLARE V_CORRECTO CHAR(1) DEFAULT 'N'; -- INDICADOR DE QUE SI EL PROCESO ESTA CORRECTO O NO
  DECLARE V_VFILENAME VARCHAR(30);
  DECLARE V_FECHA_MIN DATE;
  DECLARE V_FECHA_MAX DATE;
  DECLARE V_COUNT INT;
  DECLARE v_cantidad_dias INT;

  SET V_FEC_INICIO = SYSDATE();
  SET V_COUNT = 0;

  SELECT MAX(REQUIREDDATE) + INTERVAL 1 DAY AS fecha_max, MIN(ORDERDATE) AS fecha_min, DATEDIFF(MAX(REQUIREDDATE), MIN(ORDERDATE)) AS cantidad_dias
  INTO V_FECHA_MAX, V_FECHA_MIN, V_CANTIDAD_DIAS
  FROM ORDERS;

  WHILE V_COUNT <= V_CANTIDAD_DIAS DO
    INSERT INTO STG_DIM_TIEMPO (fecha, dia, dia_semana, dia_laboral, dia_feriado, dia_semana_corto, mes, mes_cadena, periodo, trimestre, semestre, anio)
    SELECT 
      DATE_ADD(V_FECHA_MIN, INTERVAL V_COUNT DAY) AS fecha,
      DAYOFMONTH(DATE_ADD(V_FECHA_MIN, INTERVAL V_COUNT DAY)) AS dia,
      DAYNAME(DATE_ADD(V_FECHA_MIN, INTERVAL V_COUNT DAY)) AS dia_semana,
      CASE 
        WHEN DAYNAME(DATE_ADD(V_FECHA_MIN, INTERVAL V_COUNT + 1 DAY)) IN ('Sun', 'Sat') THEN 'No'
        ELSE 'Si'
      END AS dia_laboral,
      CASE 
        WHEN DATE_ADD(V_FECHA_MIN, INTERVAL V_COUNT + 10 DAY) = '2013-05-01' THEN 'Si'
        ELSE 'No'
      END AS dia_feriado,
      SUBSTR(DAYNAME(DATE_ADD(V_FECHA_MIN, INTERVAL V_COUNT DAY)), 1, 3) AS dia_semana_corto,
      MONTH(DATE_ADD(V_FECHA_MIN, INTERVAL V_COUNT DAY)) AS mes,
      DATE_FORMAT(DATE_ADD(V_FECHA_MIN, INTERVAL V_COUNT DAY), '%b') AS mes_cadena,
      DATE_FORMAT(DATE_ADD(V_FECHA_MIN, INTERVAL V_COUNT DAY), '%Y%m') AS periodo,
      QUARTER(DATE_ADD(V_FECHA_MIN, INTERVAL V_COUNT DAY)) AS trimestre,
      QUARTER(DATE_ADD(V_FECHA_MIN, INTERVAL V_COUNT DAY)) AS semestre,
      YEAR(DATE_ADD(V_FECHA_MIN, INTERVAL V_COUNT DAY)) AS anio
    FROM DUAL;
    SET V_COUNT = V_COUNT + 1;
  END WHILE;

  SET V_FEC_FIN = SYSDATE();
  SET V_COMENTARIO = CONCAT('EL PROCESO ', V_NOMBRE_PROCESO);
  SET V_CORRECTO = 'S';

  CALL P_Insertar_Info_Proc(V_NOMBRE_PROCESO, V_FEC_INICIO, V_FEC_FIN, V_COMENTARIO, V_CANT_REG, V_CORRECTO);
END //
DELIMITER ;

