DELIMITER //
CREATE PROCEDURE ETL_STG_FACT_ORDERS(IN PI_FECHA_INICIAL VARCHAR(255), IN PI_FECHA_FINAL VARCHAR(255))
BEGIN
  DECLARE V_NOMBRE_PROCESO VARCHAR(30) DEFAULT 'ETL_STG_FACT_ORDERS';
  DECLARE V_FEC_INICIO DATETIME;
  DECLARE V_FEC_FIN DATETIME;
  DECLARE V_COMENTARIO VARCHAR(255);
  DECLARE V_CANT_REG INT DEFAULT 0;
  DECLARE V_CORRECTO CHAR(1) DEFAULT 'N';
  DECLARE v_total_diferencias INT DEFAULT 0;
  DECLARE V_FECHA_INICIO DATE;
  DECLARE V_FECHA_FIN DATE;
  
  SET v_fec_inicio = NOW();

  -- CODIGO DEL PROCESO
  SET V_FECHA_INICIO = STR_TO_DATE(PI_FECHA_INICIAL,'%Y%m%d');
  SET V_FECHA_FIN = STR_TO_DATE(PI_FECHA_FINAL,'%Y%m%d');
  
  TRUNCATE TABLE STG_FACT_ORDERS;
  
  INSERT INTO STG_FACT_ORDERS (
    IDW_CUSTOMERS, IDW_EMPLOYEES, IDW_PRODUCTS, IDW_SHIPPERS, IDW_GEOGRAFIA,
    ID_CUSTOMER, ID_EMPLOYEE, ID_ORDER,
    ORDERDATE, REQUIREDDATE, SHIPPEDDATE,
    SHIPVIA, FREIGHT, SHIPNAME, UNITPRICE,
    QUANTITY, DISCOUNT, FECHA_CARGA
  )
  SELECT 
    COALESCE((SELECT IDW_CUSTOMERS FROM STAR_O.DIM_CUSTOMERS A
              WHERE ID_CUSTOMER = V.CUSTOMERID), -1) IDW_CUSTOMERS,
    COALESCE((SELECT IDW_EMPLOYEES FROM STAR_O.DIM_EMPLOYEES A
              WHERE ID_EMPLOYEE = V.EMPLOYEEID), -1) IDW_EMPLOYEES,
    COALESCE((SELECT IDW_PRODUCTS FROM STAR_O.DIM_PRODUCTS A
              WHERE ID_PRODUCT = PRO.PRODUCTID
              AND CATEGORYID = CAT.CATEGORYID), -1) IDW_PRODUCTS,
    COALESCE((SELECT IDW_SHIPPERS FROM STAR_O.DIM_SHIPPERS A
              WHERE ID_SHIPPER = V.SHIPVIA), -1) IDW_SHIPPERS,
    COALESCE((SELECT IDW_GEOGRAFIA FROM STAR_O.DIM_GEOGRAFIA A
              WHERE IDW_GEOGRAFIA = V.ORDERID), V.ORDERID) IDW_GEOGRAFIA,
    CUSTOMERID, EMPLOYEEID, V.ORDERID, ORDERDATE, REQUIREDDATE,
    SHIPPEDDATE, SHIPVIA, FREIGHT, SHIPNAME, ORD.UNITPRICE,
    ORD.QUANTITY,
    ORD.DISCOUNT,
    NOW() FECHA_CARGA
  FROM 
    ORDERS V, 
    ORDERS.PRODUCTS PRO,
    ORDERS.CATEGORIES CAT,
    ORDERS.SUPPLIERS SUP,
    ORDERS.ORDERDETAILS ORD
  WHERE 
    PRO.PRODUCTID = SUP.SUPPLIERID
    AND PRO.CATEGORYID = CAT.CATEGORYID
    AND PRO.PRODUCTID = ORD.PRODUCTID
    AND ORD.ORDERID = V.ORDERID;

  SET V_CANT_REG = ROW_COUNT();
  COMMIT;    

  -- FIN CODIGO DEL PROCESO
  SET V_FEC_FIN = NOW();
  SET V_COMENTARIO = CONCAT('EL PROCESO ',V_NOMBRE_PROCESO,' CULMINO SATISFACTORIAMENTE');
  SET V_CORRECTO = 'S';

  CALL P_INSERTAR_INFO_PROC(V_NOMBRE_PROCESO, V_FEC_INICIO, V_FEC_FIN, V_COMENTARIO, V_CANT_REG, V_CORRECTO);
  COMMIT;

END;

SET v_fec_fin = NOW();
SET v_comentario = CONCAT('EL PROCESO ',v_nombre_proceso,' CULMINO SATISFACTORIAMENTE');
SET v_correcto = 'S';

CALL P_Insertar_Info_Proc(v_nombre_proceso, v_fec_inicio, v_fec_fin, v_comentario, v_cant_reg, v_correcto);
COMMIT;

BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
   SET v_fec_fin = NOW();
   SET v_comentario = CONCAT('ERROR AL ACTUALIZAR ',v_nombre_proceso,' ',SQLCODE,' ',SQLERRM);
   CALL P_Insertar_Info_Proc(v_nombre_proceso, v_fec_inicio, v_fec_fin, v_comentario, v_cant_reg, v_correcto);
   COMMIT;
END;
END;
//
