DELIMITER //
CREATE PROCEDURE ETL_STG_DIM_PRODUCTS()
BEGIN
    -- VARIABLES GENERALES
    DECLARE V_NOMBRE_PROCESO VARCHAR(30);
    DECLARE V_FEC_INICIO DATETIME;
    DECLARE V_FEC_FIN DATETIME;
    DECLARE V_COMENTARIO VARCHAR(255);
    DECLARE V_CANT_REG INT DEFAULT 0;
    DECLARE V_CORRECTO CHAR(1) DEFAULT 'N'; -- INDICADOR DE QUE SI EL PROCESO ESTA CORRECTO O NO

    SET V_NOMBRE_PROCESO = 'ETL_STG_DIM_PRODUCTOS';
    SET V_FEC_INICIO = NOW();

    -- CODIGO DEL PROCESO
    TRUNCATE TABLE STG_DIM_PRODUCTS;

    INSERT INTO STG_DIM_PRODUCTS (IDW_PRODUCTS, ID_PRODUCT, PRODUCTNAME, QUANTITYPERUNIT, UNITPRICE, UNITSINSTOCK, UNITSONORDER, REORDERLEVEL, DISCONTINUED, CATEGORYID, CATEGORYNAME, DESCRIPTION_CATEGORY, SUPPLIERID, SUPPLIER, SUPPLIERCONTACT, SUPPLIERTITLE, ADDRES, CITY, REGION, POSTALCODE, COUNTRY, PHONE, FAX, STAR_DATE, END_DATE, CURRENT_FLAG, LOGIN_USER_DW)
    SELECT
        COALESCE((SELECT IDW_PRODUCTS FROM STAR_O.DIM_PRODUCTS WHERE ID_PRODUCT = PRO.PRODUCTID),-1) AS IDW_PRODUCTS,
        PRO.PRODUCTID,
        PRO.PRODUCTNAME,
        PRO.QUANTITYPERUNIT,
        PRO.UNITPRICE,
        PRO.UNITSINSTOCK,
        PRO.UNITSONORDER,
        PRO.REORDERLEVEL,
        PRO.DISCONTINUED,
        CAT.CATEGORYID,
        CAT.CATEGORYNAME,
        CAT.DESCRIPTION,
        SUP.SUPPLIERID,
        SUP.COMPANYNAME,
        SUP.CONTACTNAME,
        SUP.CONTACTTITLE,
        SUP.ADDRESS,
        SUP.CITY,
        SUP.REGION,
        SUP.POSTALCODE,
        SUP.COUNTRY,
        SUP.PHONE,
        SUP.FAX,
        NOW() AS STAR_DATE,
        NOW() AS END_DATE,
        1 AS CURRENT_FLAG,
        USER() AS LOGIN_USER_DW
    FROM
        STG_PRODUCTS PRO
        INNER JOIN STG_SUPPLIERS SUP ON PRO.SUPPLIERID = SUP.SUPPLIERID
        INNER JOIN STG_CATEGORIES CAT ON PRO.CATEGORYID = CAT.CATEGORYID;

    SET V_CANT_REG = ROW_COUNT();
    COMMIT;

    SELECT COUNT(*) INTO V_CANT_REG FROM STG_DIM_PRODUCTS;

    -- FIN CODIGO DEL PROCESO
    SET V_FEC_FIN = NOW();
    SET V_COMENTARIO = CONCAT('EL PROCESO ', V_NOMBRE_PROCESO, ' CULMINO SATISFACTORIAMENTE');
    SET V_CORRECTO = 'S';

    CALL P_Insertar_Info_Proc(V_NOMBRE_PROCESO, V_FEC_INICIO, V_FEC_FIN, V_COMENTARIO, V_CANT_REG, V_CORRECTO);
    COMMIT;

    -- Manejo de errores
    
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
    BEGIN
        SET V_FEC_FIN = NOW();
        SET V_COMENTARIO = CONCAT('ERROR AL ACTUALIZAR ', V_NOMBRE_PROCESO, ' ', SQLCODE, ' ', SQLERRM);
        CALL P_Insertar_Info_Proc(V_NOMBRE_PROCESO, V_FEC_INICIO, V_FEC_FIN, V_COMENTARIO, V_CANT_REG,
V_CORRECTO);
COMMIT;
END;
END

END $$
DELIMITER ;
