DELIMITER $$
CREATE PROCEDURE ETL_STG_DIM_SHIPPERS()
BEGIN
-- VARIABLES GENERALES
DECLARE V_NOMBRE_PROCESO VARCHAR(30) DEFAULT 'ETL_STG_DIM_SHIPPERS';
DECLARE V_FEC_INICIO DATE;
DECLARE V_FEC_FIN DATE;
DECLARE V_COMENTARIO VARCHAR(255);
DECLARE V_CANT_REG INT DEFAULT 0;
DECLARE V_CORRECTO CHAR(1) DEFAULT 'N'; -- INDICADOR DE QUE SI EL PROCESO ESTA CORRECTO O NO
-- VARIABLES DEL PROCESO
DECLARE V_TOTAL_DIFERENCIAS INT DEFAULT 0;

SET V_FEC_INICIO = SYSDATE();

-- CODIGO DEL PROCESO
TRUNCATE TABLE STG_DIM_SHIPPERS;

INSERT INTO STG_DIM_SHIPPERS (
IDW_SHIPPERS,
ID_SHIPPER,
SHIPPERS,
PHONE,
START_DATE,
END_DATE,
CURRENT_FLAG,
LOGIN_USER_DW
)
SELECT
IFNULL((SELECT IDW_SHIPPERS FROM STAR_O.DIM_SHIPPERS WHERE ID_SHIPPER = SCR.SHIPPERID), -1) AS IDW_SHIPPERS,
SCR.SHIPPERID,
SCR.COMPANYNAME,
SCR.PHONE,
NOW() AS START_DATE,
NOW() AS END_DATE,
1 AS CURRENT_FLAG,
Sys_Context('USERENV','OS_USER') AS LOGIN_USER_DW
FROM STG_SHIPPERS SCR;

SET V_CANT_REG = ROW_COUNT();
COMMIT;

-- FIN CODIGO DEL PROCESO
SET V_FEC_FIN = SYSDATE();
SET V_COMENTARIO = CONCAT('EL PROCESO ', V_NOMBRE_PROCESO, ' CULMINO SATISFACTORIAMENTE ');
SET V_CORRECTO = 'S';

CALL P_Insertar_Info_Proc(
V_NOMBRE_PROCESO,
V_FEC_INICIO,
V_FEC_FIN,
V_COMENTARIO,
V_CANT_REG,
V_CORRECTO
);
COMMIT;
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
SET V_FEC_FIN = SYSDATE();
SET V_COMENTARIO = CONCAT('ERROR AL ACTUALIZAR ', V_NOMBRE_PROCESO, ' ', SQLCODE(), ' ', SQLERRM());
CALL P_Insertar_Info_Proc(
V_NOMBRE_PROCESO,
V_FEC_INICIO,
V_FEC_FIN,
V_COMENTARIO,
V_CANT_REG,
V_CORRECTO
);
COMMIT;
END;
END;
END$$
DELIMITER ;

