DELIMITER $$
CREATE PROCEDURE ETL_STG_DIM_EMPLOYEES()
BEGIN
-- VARIABLES GENERALES
DECLARE V_NOMBRE_PROCESO VARCHAR(30) DEFAULT 'ETL_STG_DIM_EMPLOYEES';
DECLARE V_FEC_INICIO DATE;
DECLARE V_FEC_FIN DATE;
DECLARE V_COMENTARIO VARCHAR(255);
DECLARE V_CANT_REG INT DEFAULT 0;
DECLARE V_CORRECTO CHAR(1) DEFAULT 'N'; -- INDICADOR DE QUE SI EL PROCESO ESTA CORRECTO O NO
-- VARIABLES DEL PROCESO
DECLARE v_total_diferencias INT DEFAULT 0;

SET V_FEC_INICIO = NOW();

-- CODIGO DEL PROCESO

TRUNCATE TABLE STG_DIM_EMPLOYEES;

INSERT INTO STG_DIM_EMPLOYEES (
IDW_EMPLOYEES,
ID_EMPLOYEE,
LASTNAME,
FIRSTNAME,
TITLE,
TITLEOFCOURTESY,
BIRTHDATE,
HIREDATE,
ADDRESS,
CITY,
REGION,
POSTALCODE,
COUNTRY,
HOMEPHONE,
EXTENSION,
NOTES,
REPORTSTO,
STAR_DATE,
END_DATE,
CURRENT_FLAG,
LOGIN_USER_DW
)
SELECT
COALESCE(
(
SELECT IDW_EMPLOYEES
FROM STAR_O.DIM_EMPLOYEES A
WHERE ID_EMPLOYEE = s.EMPLOYEEID
),
-1
) IDW_EMPLOYEES,
s.EMPLOYEEID,
s.LASTNAME,
s.FIRSTNAME,
s.TITLE,
s.TITLEOFCOURTESY,
s.BIRTHDATE,
s.HIREDATE,
s.ADDRESS,
s.CITY,
s.REGION,
s.POSTALCODE,
s.COUNTRY,
s.HOMEPHONE,
s.EXTENSION,
s.NOTES,
s.REPORTSTO,
NOW() AS STAR_DATE,
NOW() AS END_DATE,
1 CURRENT_FLAG,
USER() LOGIN_USER_DW
FROM STG_EMPLOYEES s;

SET V_CANT_REG = ROW_COUNT();
COMMIT;

-- FIN CODIGO DEL PROCESO
SET V_FEC_FIN = NOW();
SET V_COMENTARIO = CONCAT('EL PROCESO ', V_NOMBRE_PROCESO, ' CULMINO SATISFACTORIAMENTE ');
SET V_CORRECTO = 'S';

CALL P_Insertar_Info_Proc(V_NOMBRE_PROCESO,
V_FEC_INICIO,
V_FEC_FIN,
V_COMENTARIO,
V_CANT_REG,
V_CORRECTO );
COMMIT;

-- Manejo de errores
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	SET V_FEC_FIN = NOW();
	SET V_COMENTARIO = CONCAT('ERROR AL ACTUALIZAR ', V_NOMBRE_PROCESO, ' ', SQLCODE, ' ', SQLERRM);
	CALL P_Insertar_Info_Proc(V_NOMBRE_PROCESO,
	V_FEC_INICIO,
	V_FEC_FIN,
	V_COMENTARIO,
	V_CANT_REG,
	V_CORRECTO);
	COMMIT;
	END;
	END;
END $$
DELIMITER ;
